
  BASE_API_URL = "https://api.proof.market.nil.foundation"
  DBMS_DEFAULT_DATABASE = "market"
  API_VERSION = "v0_0"
  REVALIDATE_DATA_INTERVAL = "7000"
  READONLY_USER = "readonly"
  SITE_DEFAULT_TITLE = "=nil; Foundation - Proof Market"
  GA_TRACKING_ID = "G-ZMGSS2KNCJ"
  PROOFMARKET_TOOLCHAIN_REPO = "https://github.com/NilFoundation/proof-market-toolchain"
  SENTRY_DSN = "https://25060f5edf144018919e2fe4e3b4bb37@o4504243377995776.ingest.sentry.io/4504243621134336"
  CIRCUIT_DEVELOPER_GUIDE_URL = "https://docs.nil.foundation/proof-market/market/user-guides/circuit-developer"
  API_RESPONSE_WAIT_TIMEOUT = "120000"

