BASE_API_URL = ""
DBMS_DEFAULT_DATABASE = ""
API_VERSION = ""
REVALIDATE_DATA_INTERVAL = ""
READONLY_USER = ""
SITE_DEFAULT_TITLE = ""
GA_TRACKING_ID = ""
PROOFMARKET_TOOLCHAIN_REPO = ""
SENTRY_DSN = ""
GOOGLE_AUTH_CLIENT_ID = ""
CIRCUIT_DEVELOPER_GUIDE_URL = ""
API_RESPONSE_WAIT_TIMEOUT = ""
