name: Build

on:
  # Triggers the workflow on every pull-request
  pull_request:
  # Allows to trigger workflow manually
  workflow_dispatch:
  # Allows to call from another workflow
  workflow_call:

jobs:
  build:
    name: Build
    runs-on: [self-hosted, nodejs-runner]
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Nodejs
      uses: actions/setup-node@v3
      with:
        node-version: 16.x

    - name: Cache dependencies
      id: cache-node-modules
      uses: actions/cache@v3
      env:
        CACHE_NAME: cache-node-modules
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-cache-
          ${{ runner.os }}-

    - name: Install dependencies
      if: ${{ steps.cache-node-modules.outputs.cache-hit != 'true' }}
      run: |
        npm config set "//npm.pkg.github.com/:_authToken" ${{ secrets.AUTH_TOKEN }}
        npm ci

    - name: Setup env
      run: |
        set REACT_APP_BASE_API_URL=${{ secrets.BASE_API_URL }}
        set REACT_APP_DBMS_DEFAULT_DATABASE=${{ secrets.DBMS_DEFAULT_DATABASE }}
        set REACT_APP_SENTRY_DSN=${{ secrets.SENTRY_DSN }}
        set REACT_APP_SITE_EMAIL=${{ secrets.SITE_EMAIL }}
        set REACT_APP_READONLY_USER=${{ secrets.READONLY_USER }}

    - name: Build
      run: |
        CI=false
        npm run build

    - name: Pack build results
      run: tar -czf build-${{ github.sha }}.tar.gz build

    - name: Upload workflow artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-${{ github.sha }}
        path: build-${{ github.sha }}.tar.gz
        if-no-files-found: error
        retention-days: 10
