name: Build

on:
  # Triggers the workflow on every pull-request
  pull_request:
  # Allows to trigger workflow manually
  workflow_dispatch:
  # Allows to call from another workflow
  workflow_call:

jobs:
  build:
    name: Build
    runs-on: [ubuntu-latest]
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Nodejs
      uses: actions/setup-node@v3
      with:
        node-version: 16.x

    - name: Install dependencies
      run: |
        npm config set "//npm.pkg.github.com/:_authToken" ${{ secrets.AUTH_TOKEN }}
        npm ci

    - name: Setup env
      run: |
        touch .env.local
        echo "REACT_APP_BASE_API_URL=${{ secrets.BASE_API_URL }}" >> .env.local
        echo "REACT_APP_DBMS_DEFAULT_DATABASE=${{ secrets.DBMS_DEFAULT_DATABASE }}" >> .env.local
        echo "REACT_APP_SENTRY_DSN=${{ secrets.SENTRY_DSN }}" >> .env.local
        echo "REACT_APP_FORMSPREE_FORM_ID=${{ secrets.FORMSPREE_FORM_ID }}" >> .env.local
        echo "REACT_APP_READONLY_USER=${{ secrets.READONLY_USER }}" >> .env.local
        echo "REACT_APP_SITE_DEFAULT_TITLE=${{ secrets.SITE_DEFAULT_TITLE }}" >> .env.local
        echo "REACT_APP_GA_TRACKING_ID=${{ secrets.GA_TRACKING_ID }}" >> .env.local

    - name: Build
      run: |
        CI=false
        npm run build

    - name: Pack build results
      run: tar -czf build-${{ github.sha }}.tar.gz build

    - name: Upload workflow artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-${{ github.sha }}
        path: build-${{ github.sha }}.tar.gz
        if-no-files-found: error
        retention-days: 10


# Update test stand on every pull-request
    - name: Install SSH Key
      if: ${{ github.event_name == 'pull_request' }}
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.TEST_STAND_SSH_KEY }}
        known_hosts: 'placeholder'

    - name: Adding known hosts
      if: ${{ github.event_name == 'pull_request' }}
      run: ssh-keyscan -H ${{ secrets.TEST_STAND_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy on test stand
      if: ${{ github.event_name == 'pull_request' }}
      env:
        HOST: ${{ secrets.TEST_STAND_HOST }}
        USER: ${{ secrets.TEST_STAND_USER }}
        TARGET_DIR: '/home/staging/proof.market.nil.foundation.test-stand'
        OPTIONS: '-avz --progress --delete'
      run: rsync ${{ env.OPTIONS }} build/ ${{ env.USER }}@${{ env.HOST }}:${{ env.TARGET_DIR }}
