name: Deploy

on:
  # Triggers the workflow on push to master branch
  push:
    branches: [ master ]
  # Allows to trigger workflow manually
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    name: Build

  deploy:
    name: Deploy
    runs-on: [ubuntu-latest]
    needs: [build]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build-${{ github.sha }}

      - name: Deploy app
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
