name: Deploy
# This workflow is triggered manually.
# It deploys the app to GitHub Pages and optionally updates proof.market repository.

on:
  workflow_dispatch:
    inputs:
      update-proof-market:
        type: boolean
        default: true
        description: Update proof.market repository also
      commit:
        description: 'Commit SHA1'
        required: false
        default: ''
        type: string

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    secrets: inherit
    with:
      environment: github-pages
      commit: ${{ inputs.commit || github.sha }}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: github-pages
    needs: [build]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build-${{ github.sha }}

      - name: Extract build results
        run: tar -xf build-${{ github.sha }}.tar.gz

      - name: Deploy app
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build

      - name: Overwrite CNAME for proof.market repository
        if: ${{ inputs.update-proof-market }}
        run: echo ${{ secrets.PROOF_MARKET_REPO_DOMAIN }} > 'build/CNAME'

      - name: Update proof.market repository
        if: ${{ inputs.update-proof-market }}
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.PROOF_MARKET_REPO_PUSH_TOKEN }}
        with:
          source-directory: 'build'
          destination-github-username: ${{ secrets.PROOF_MARKET_REPO_OWNER }}
          destination-repository-name: ${{ secrets.PROOF_MARKET_REPO_NAME }}
          target-branch: gh-pages
