name: Version
# This workflow is triggered on push to master branch and can be triggered manually.
# It pushes new package version to external storage.

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "src/**"

jobs:
  build:
    name: Version
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Update version
      run: |
        npm version ${{ inputs.release_type || 'patch' }}
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.PUSH_TOKEN }}
        branch: master
        tags: true
