name: Release
# This workflow is triggered when a tag in master branch is created.
# It creates a release with current version.

on:
  push:
    tags:
      - 'v*'
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          token: ${{ secrets.PUSH_TOKEN }}
